version: '3'
services:
  nginx:
    image: "jackwang316/multi-nginx-10-14"
    mem_limit: 128m
    hostname: nginx 
    ports: 
      - '80:80'
    restart: always
  server:
    image: jackwang316/multi-server-10-14
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: jackwang316/multi-worker-10-14
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  client:
    image: jackwang316/multi-client-10-14
    mem_limit: 128m
    hostname: client
